version: "3.9"

services:
  openvpn-out:
    image: ghcr.io/lanlan13-14/openvpn-out:latest
    container_name: openvpn-out
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "1194:1194/udp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    sysctls:
      net.ipv6.conf.all.forwarding: "1"
      net.ipv6.conf.default.forwarding: "1"
    volumes:
      - ./env:/env:ro
      - ./openvpn:/openvpn
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
