version: "3.9"

services:
  openvpn-out:
    build:
      context: .
      args:
        SING_BOX_VERSION: "1.12.0"
    image: openvpn-out:local
    container_name: openvpn-out
    network_mode: host
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    devices:
      - /dev/net/tun
    volumes:
      - ./env:/env:ro
      - ./openvpn:/openvpn
    restart: unless-stopped
